function result_sep = encontra_ponto_separacao(Duracao, i,...
    referencia_tamanho)

val_atual = Duracao(i,1);
val_seguinte1 = Duracao(i+1,1);
val_seguinte2 = Duracao(i+2,1);
val_seguinte3 = Duracao(i+3,1);
val_seguinte4 = Duracao(i+4,1);
val_seguinte5 = Duracao(i+5,1);

sub_seguinte1 = val_atual - val_seguinte1;
sub_seguinte2 = val_atual - val_seguinte2;
sub_seguinte3 = val_atual - val_seguinte3;
sub_seguinte4 = val_atual - val_seguinte4;
sub_seguinte5 = val_atual - val_seguinte5;

if sub_seguinte1 >= referencia_tamanho && ...
   sub_seguinte2 >= referencia_tamanho && ...
   sub_seguinte3 >= referencia_tamanho && ...
   sub_seguinte4 >= referencia_tamanho && ...
   sub_seguinte5 >= referencia_tamanho && ...
   val_seguinte1 < referencia_tamanho && ...
   val_seguinte2 < referencia_tamanho && ...
   val_seguinte3 < referencia_tamanho && ...
   val_seguinte4 < referencia_tamanho && ...
   val_seguinte5 < referencia_tamanho 
result_sep = true;
else
    result_sep = false;

end