Microfone_eletreto = openBin('0123_ch1.bin', inf, 0, 200e3);

Dir_X = openBin('0123_ch2.bin', inf, 0, 200e3);

Dir_Y = openBin('0123_ch3.bin', inf, 0, 200e3);

% tic;
% [linhas_PE, linhas_PI, trans_PI, mov_ini_PI, ponto_sep_PE_PI,...
%     sep_PE, sinal_linhas_PI, sinal_trans_PI] = ...
%     separaimpressao (Microfone_eletreto, Dir_X, Dir_Y, 200e3,...
%     1, 2, 4, 'Microfone de eletreto'); %#ok<*ASGLU> 
% toc;
% 
% tic;
% [linhas_PE, linhas_PI, trans_PI, mov_ini_PI, ponto_sep_PE_PI,...
%     sep_PE, sinal_linhas_PI, sinal_trans_PI] = ...
%     separaimpressao (Microfone_eletreto, Dir_X, Dir_Y, 200e3,...
%     1, 1, 3, 'Microfone de eletreto');
% toc;


tic;
[linhas_PE, linhas_PI, trans_PI, mov_ini_PI, ponto_sep_PE_PI,...
    sep_PE, sinal_linhas_PI, sinal_trans_PI] = ...
    separaimpressao (Microfone_eletreto, Dir_X, Dir_Y, 200e3,...
    1, 0, 5, 'Microfone de eletreto'); %#ok<*ASGLU> 
toc;

tic;
[linhas_PE, linhas_PI, trans_PI, mov_ini_PI, ponto_sep_PE_PI,...
    sep_PE, sinal_linhas_PI, sinal_trans_PI] = ...
    separaimpressao (Microfone_eletreto, Dir_X, Dir_Y, 200e3,...
    1, 0, 6, 'Microfone de eletreto'); %#ok<*ASGLU> 
toc;

